# Site settings
title: Coding Girl
email:
description: Ganna Androsova's journey into Data Science

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://androsova.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: "UA-114738908-1"
addthis_id: ra-5a92e035ce92f929
disqus_account: androsova

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  #- title: twitter
  #  url: https://twitter.com/lantoniotrento
  #- title: facebook
  #  url: https://facebook.com/lantoniotrento
  #- title: google-plus
  #  url: https://plus.google.com/+AntoniotrentoIt
  - title: linkedin
    url: https://www.linkedin.com/in/ganna-androsova/
  - title: github
    url: https://github.com/androsova
  - title: university
    url: https://wwwen.uni.lu/lcsb/people/ganna_androsova

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
